# Generated by Django 5.0.1 on 2024-02-04 12:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='second',
            field=tinymce.models.HTMLField(max_length=100),
        ),
    ]
