# Generated by Django 5.0.1 on 2024-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_alter_new_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='first',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='second',
            field=models.TextField(max_length=100),
        ),
    ]
