# Generated by Django 5.0.1 on 2024-02-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_alter_new_first_alter_new_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='second',
            field=models.CharField(max_length=100),
        ),
    ]
