# Generated by Django 5.0.1 on 2024-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ima_1', models.CharField(max_length=50)),
                ('mai1', models.CharField(max_length=50)),
                ('mai2', models.CharField(max_length=100)),
            ],
        ),
    ]
