# Generated by Django 5.0.1 on 2024-02-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solo',
            name='ima_1',
        ),
    ]
