# Generated by Django 5.0.1 on 2024-02-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_solo_ima_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='mai3',
            field=models.CharField(default='net', max_length=100),
        ),
    ]
